FROM golang:1.20 AS build

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download && go mod tidy

COPY . ./
RUN CGO_ENABLED=0 go build -o ./build/main ./cmd

FROM scratch

EXPOSE 7070

WORKDIR /app

COPY --from=build /app/certs ./certs
COPY --from=build /app/build/main ./main
COPY --from=build /app/logs ./logs

ENTRYPOINT ["./main"]
