version: '3.9'

services:
  postgres:
    hostname: db
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  server:
    hostname: server
    image: atom/server
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - APP_ADDR=0.0.0.0
      - APP_MAX_STREAMS=8
      - APP_PORT=7070
      - DB_HOST=db
      - DB_NAME=test
      - DB_PASS=pass
      - DB_PORT=5432
      - DB_USER=admin
    ports:
      - 7070:7070
    depends_on:
      postgres:
        condition: service_healthy
  client:
    container_name: client
    image: atom/client
    build:
      context: .
      dockerfile: Dockerfile-client
#    command: "-a=0.0.0.0 -p=7070 "
    stdin_open: true
    tty: true
    command: sh
    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_started

networks:
  default:

